{% set name = "pysp2" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysp2-{{ version }}.tar.gz
  sha256: dab7e2e83754db7f2d69a0d7d30876d9a38b41723faf1f36bba743d83642d668

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - matplotlib-base
    - numpy
    - pandas
    - scipy
    - xarray
    - xlrd
    - act-atmos

test:
  imports:
    - pysp2
  commands:
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests/*.py

about:
  home: https://pypi.org/project/pysp2/
  summary: A package for analyzing Single Particle Soot Photometer (SP2) data
  description: |
    This is a python package for processing and visualizing SP2 data. It is based
    off of the IGOR code developed by Droplet Measurement Technologies.
    PySP2 currently supports processing all raw SP2 data (.sp2b, .hk, .ini) files 
    into mass and number size distributions. It can plot individual waveforms as
    well as particle size distributions. Its file format is based off of the standard
    provided by the Atmospheric Community Toolkit which is based around xarray.
    PySP2 is currently used by the Department of Energy Atmospheric Radiation
    Measurment (ARM) Facility in order to process SP2 observations during field
    deployments such as TRACER and SAIL.
  dev_url: https://github.com/ARM-DOE/PySP2
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rcjackson
